set tabstop=4

""""""""""""""
"" General  ""
""  Changes ""
""""""""""""""

" use vim settings over vi settings
set nocompatible

" security? TODO: Find out what this means in this context
set modelines=0

"""""""""""""""
"" UI changes""
"""""""""""""""

" show number lines
set number

" show matching parenthesis
set showmatch

" syntax highlighting
syntax on
set synmaxcol=512
filetype plugin on

" stop unnecessary rendering
" set lazyredraw

" highlight cursor
" set cursorline

" split style
set fillchars=vert:▒

" tree style file explorer
let g:netrw_liststyle=3
let g:netrw_browse_split=4
let g:netrw_winsize=25
